// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// BudgetRule is the predicate function for budgetrule builders.
type BudgetRule func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Goal is the predicate function for goal builders.
type Goal func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
