// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/budgetrule"
	"backend/ent/predicate"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetRuleUpdate is the builder for updating BudgetRule entities.
type BudgetRuleUpdate struct {
	config
	hooks    []Hook
	mutation *BudgetRuleMutation
}

// Where appends a list predicates to the BudgetRuleUpdate builder.
func (_u *BudgetRuleUpdate) Where(ps ...predicate.BudgetRule) *BudgetRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLabel sets the "label" field.
func (_u *BudgetRuleUpdate) SetLabel(v string) *BudgetRuleUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *BudgetRuleUpdate) SetNillableLabel(v *string) *BudgetRuleUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *BudgetRuleUpdate) SetCategory(v string) *BudgetRuleUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *BudgetRuleUpdate) SetNillableCategory(v *string) *BudgetRuleUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetPercentage sets the "percentage" field.
func (_u *BudgetRuleUpdate) SetPercentage(v float64) *BudgetRuleUpdate {
	_u.mutation.ResetPercentage()
	_u.mutation.SetPercentage(v)
	return _u
}

// SetNillablePercentage sets the "percentage" field if the given value is not nil.
func (_u *BudgetRuleUpdate) SetNillablePercentage(v *float64) *BudgetRuleUpdate {
	if v != nil {
		_u.SetPercentage(*v)
	}
	return _u
}

// AddPercentage adds value to the "percentage" field.
func (_u *BudgetRuleUpdate) AddPercentage(v float64) *BudgetRuleUpdate {
	_u.mutation.AddPercentage(v)
	return _u
}

// SetColor sets the "color" field.
func (_u *BudgetRuleUpdate) SetColor(v string) *BudgetRuleUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *BudgetRuleUpdate) SetNillableColor(v *string) *BudgetRuleUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BudgetRuleUpdate) SetCreatedAt(v time.Time) *BudgetRuleUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BudgetRuleUpdate) SetNillableCreatedAt(v *time.Time) *BudgetRuleUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *BudgetRuleUpdate) SetOwnerID(id int) *BudgetRuleUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *BudgetRuleUpdate) SetNillableOwnerID(id *int) *BudgetRuleUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *BudgetRuleUpdate) SetOwner(v *User) *BudgetRuleUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the BudgetRuleMutation object of the builder.
func (_u *BudgetRuleUpdate) Mutation() *BudgetRuleMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *BudgetRuleUpdate) ClearOwner() *BudgetRuleUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BudgetRuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BudgetRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BudgetRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BudgetRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BudgetRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(budgetrule.Table, budgetrule.Columns, sqlgraph.NewFieldSpec(budgetrule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(budgetrule.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(budgetrule.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Percentage(); ok {
		_spec.SetField(budgetrule.FieldPercentage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPercentage(); ok {
		_spec.AddField(budgetrule.FieldPercentage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(budgetrule.FieldColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(budgetrule.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budgetrule.OwnerTable,
			Columns: []string{budgetrule.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budgetrule.OwnerTable,
			Columns: []string{budgetrule.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budgetrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BudgetRuleUpdateOne is the builder for updating a single BudgetRule entity.
type BudgetRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BudgetRuleMutation
}

// SetLabel sets the "label" field.
func (_u *BudgetRuleUpdateOne) SetLabel(v string) *BudgetRuleUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *BudgetRuleUpdateOne) SetNillableLabel(v *string) *BudgetRuleUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *BudgetRuleUpdateOne) SetCategory(v string) *BudgetRuleUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *BudgetRuleUpdateOne) SetNillableCategory(v *string) *BudgetRuleUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetPercentage sets the "percentage" field.
func (_u *BudgetRuleUpdateOne) SetPercentage(v float64) *BudgetRuleUpdateOne {
	_u.mutation.ResetPercentage()
	_u.mutation.SetPercentage(v)
	return _u
}

// SetNillablePercentage sets the "percentage" field if the given value is not nil.
func (_u *BudgetRuleUpdateOne) SetNillablePercentage(v *float64) *BudgetRuleUpdateOne {
	if v != nil {
		_u.SetPercentage(*v)
	}
	return _u
}

// AddPercentage adds value to the "percentage" field.
func (_u *BudgetRuleUpdateOne) AddPercentage(v float64) *BudgetRuleUpdateOne {
	_u.mutation.AddPercentage(v)
	return _u
}

// SetColor sets the "color" field.
func (_u *BudgetRuleUpdateOne) SetColor(v string) *BudgetRuleUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *BudgetRuleUpdateOne) SetNillableColor(v *string) *BudgetRuleUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BudgetRuleUpdateOne) SetCreatedAt(v time.Time) *BudgetRuleUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BudgetRuleUpdateOne) SetNillableCreatedAt(v *time.Time) *BudgetRuleUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *BudgetRuleUpdateOne) SetOwnerID(id int) *BudgetRuleUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *BudgetRuleUpdateOne) SetNillableOwnerID(id *int) *BudgetRuleUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *BudgetRuleUpdateOne) SetOwner(v *User) *BudgetRuleUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the BudgetRuleMutation object of the builder.
func (_u *BudgetRuleUpdateOne) Mutation() *BudgetRuleMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *BudgetRuleUpdateOne) ClearOwner() *BudgetRuleUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the BudgetRuleUpdate builder.
func (_u *BudgetRuleUpdateOne) Where(ps ...predicate.BudgetRule) *BudgetRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BudgetRuleUpdateOne) Select(field string, fields ...string) *BudgetRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BudgetRule entity.
func (_u *BudgetRuleUpdateOne) Save(ctx context.Context) (*BudgetRule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BudgetRuleUpdateOne) SaveX(ctx context.Context) *BudgetRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BudgetRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BudgetRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BudgetRuleUpdateOne) sqlSave(ctx context.Context) (_node *BudgetRule, err error) {
	_spec := sqlgraph.NewUpdateSpec(budgetrule.Table, budgetrule.Columns, sqlgraph.NewFieldSpec(budgetrule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BudgetRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, budgetrule.FieldID)
		for _, f := range fields {
			if !budgetrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != budgetrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(budgetrule.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(budgetrule.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Percentage(); ok {
		_spec.SetField(budgetrule.FieldPercentage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPercentage(); ok {
		_spec.AddField(budgetrule.FieldPercentage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(budgetrule.FieldColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(budgetrule.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budgetrule.OwnerTable,
			Columns: []string{budgetrule.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budgetrule.OwnerTable,
			Columns: []string{budgetrule.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BudgetRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budgetrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
