// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/budgetrule"
	"backend/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetRuleDelete is the builder for deleting a BudgetRule entity.
type BudgetRuleDelete struct {
	config
	hooks    []Hook
	mutation *BudgetRuleMutation
}

// Where appends a list predicates to the BudgetRuleDelete builder.
func (_d *BudgetRuleDelete) Where(ps ...predicate.BudgetRule) *BudgetRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BudgetRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BudgetRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BudgetRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(budgetrule.Table, sqlgraph.NewFieldSpec(budgetrule.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BudgetRuleDeleteOne is the builder for deleting a single BudgetRule entity.
type BudgetRuleDeleteOne struct {
	_d *BudgetRuleDelete
}

// Where appends a list predicates to the BudgetRuleDelete builder.
func (_d *BudgetRuleDeleteOne) Where(ps ...predicate.BudgetRule) *BudgetRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BudgetRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{budgetrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BudgetRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
