// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/budgetrule"
	"backend/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BudgetRule is the model entity for the BudgetRule schema.
type BudgetRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Percentage holds the value of the "percentage" field.
	Percentage float64 `json:"percentage,omitempty"`
	// Color holds the value of the "color" field.
	Color string `json:"color,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BudgetRuleQuery when eager-loading is set.
	Edges             BudgetRuleEdges `json:"edges"`
	user_budget_rules *int
	selectValues      sql.SelectValues
}

// BudgetRuleEdges holds the relations/edges for other nodes in the graph.
type BudgetRuleEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BudgetRuleEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BudgetRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case budgetrule.FieldPercentage:
			values[i] = new(sql.NullFloat64)
		case budgetrule.FieldID:
			values[i] = new(sql.NullInt64)
		case budgetrule.FieldLabel, budgetrule.FieldCategory, budgetrule.FieldColor:
			values[i] = new(sql.NullString)
		case budgetrule.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case budgetrule.ForeignKeys[0]: // user_budget_rules
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BudgetRule fields.
func (_m *BudgetRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case budgetrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case budgetrule.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case budgetrule.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case budgetrule.FieldPercentage:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field percentage", values[i])
			} else if value.Valid {
				_m.Percentage = value.Float64
			}
		case budgetrule.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = value.String
			}
		case budgetrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case budgetrule.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_budget_rules", value)
			} else if value.Valid {
				_m.user_budget_rules = new(int)
				*_m.user_budget_rules = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BudgetRule.
// This includes values selected through modifiers, order, etc.
func (_m *BudgetRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the BudgetRule entity.
func (_m *BudgetRule) QueryOwner() *UserQuery {
	return NewBudgetRuleClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this BudgetRule.
// Note that you need to call BudgetRule.Unwrap() before calling this method if this BudgetRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BudgetRule) Update() *BudgetRuleUpdateOne {
	return NewBudgetRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BudgetRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BudgetRule) Unwrap() *BudgetRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BudgetRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BudgetRule) String() string {
	var builder strings.Builder
	builder.WriteString("BudgetRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("percentage=")
	builder.WriteString(fmt.Sprintf("%v", _m.Percentage))
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(_m.Color)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BudgetRules is a parsable slice of BudgetRule.
type BudgetRules []*BudgetRule
