// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/budgetrule"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetRuleCreate is the builder for creating a BudgetRule entity.
type BudgetRuleCreate struct {
	config
	mutation *BudgetRuleMutation
	hooks    []Hook
}

// SetLabel sets the "label" field.
func (_c *BudgetRuleCreate) SetLabel(v string) *BudgetRuleCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *BudgetRuleCreate) SetCategory(v string) *BudgetRuleCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetPercentage sets the "percentage" field.
func (_c *BudgetRuleCreate) SetPercentage(v float64) *BudgetRuleCreate {
	_c.mutation.SetPercentage(v)
	return _c
}

// SetColor sets the "color" field.
func (_c *BudgetRuleCreate) SetColor(v string) *BudgetRuleCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BudgetRuleCreate) SetCreatedAt(v time.Time) *BudgetRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BudgetRuleCreate) SetNillableCreatedAt(v *time.Time) *BudgetRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *BudgetRuleCreate) SetOwnerID(id int) *BudgetRuleCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_c *BudgetRuleCreate) SetNillableOwnerID(id *int) *BudgetRuleCreate {
	if id != nil {
		_c = _c.SetOwnerID(*id)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *BudgetRuleCreate) SetOwner(v *User) *BudgetRuleCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the BudgetRuleMutation object of the builder.
func (_c *BudgetRuleCreate) Mutation() *BudgetRuleMutation {
	return _c.mutation
}

// Save creates the BudgetRule in the database.
func (_c *BudgetRuleCreate) Save(ctx context.Context) (*BudgetRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BudgetRuleCreate) SaveX(ctx context.Context) *BudgetRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BudgetRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BudgetRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BudgetRuleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := budgetrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BudgetRuleCreate) check() error {
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "BudgetRule.label"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "BudgetRule.category"`)}
	}
	if _, ok := _c.mutation.Percentage(); !ok {
		return &ValidationError{Name: "percentage", err: errors.New(`ent: missing required field "BudgetRule.percentage"`)}
	}
	if _, ok := _c.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "BudgetRule.color"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BudgetRule.created_at"`)}
	}
	return nil
}

func (_c *BudgetRuleCreate) sqlSave(ctx context.Context) (*BudgetRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BudgetRuleCreate) createSpec() (*BudgetRule, *sqlgraph.CreateSpec) {
	var (
		_node = &BudgetRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(budgetrule.Table, sqlgraph.NewFieldSpec(budgetrule.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(budgetrule.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(budgetrule.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Percentage(); ok {
		_spec.SetField(budgetrule.FieldPercentage, field.TypeFloat64, value)
		_node.Percentage = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(budgetrule.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(budgetrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budgetrule.OwnerTable,
			Columns: []string{budgetrule.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_budget_rules = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BudgetRuleCreateBulk is the builder for creating many BudgetRule entities in bulk.
type BudgetRuleCreateBulk struct {
	config
	err      error
	builders []*BudgetRuleCreate
}

// Save creates the BudgetRule entities in the database.
func (_c *BudgetRuleCreateBulk) Save(ctx context.Context) ([]*BudgetRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BudgetRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BudgetRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BudgetRuleCreateBulk) SaveX(ctx context.Context) []*BudgetRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BudgetRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BudgetRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
