// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/goal"
	"backend/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Goal is the model entity for the Goal schema.
type Goal struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Target holds the value of the "target" field.
	Target float64 `json:"target,omitempty"`
	// Current holds the value of the "current" field.
	Current float64 `json:"current,omitempty"`
	// Deadline holds the value of the "deadline" field.
	Deadline time.Time `json:"deadline,omitempty"`
	// Color holds the value of the "color" field.
	Color string `json:"color,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GoalQuery when eager-loading is set.
	Edges        GoalEdges `json:"edges"`
	user_goals   *int
	selectValues sql.SelectValues
}

// GoalEdges holds the relations/edges for other nodes in the graph.
type GoalEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GoalEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Goal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case goal.FieldTarget, goal.FieldCurrent:
			values[i] = new(sql.NullFloat64)
		case goal.FieldID:
			values[i] = new(sql.NullInt64)
		case goal.FieldName, goal.FieldColor:
			values[i] = new(sql.NullString)
		case goal.FieldDeadline, goal.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case goal.ForeignKeys[0]: // user_goals
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Goal fields.
func (_m *Goal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case goal.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case goal.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case goal.FieldTarget:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field target", values[i])
			} else if value.Valid {
				_m.Target = value.Float64
			}
		case goal.FieldCurrent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field current", values[i])
			} else if value.Valid {
				_m.Current = value.Float64
			}
		case goal.FieldDeadline:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deadline", values[i])
			} else if value.Valid {
				_m.Deadline = value.Time
			}
		case goal.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = value.String
			}
		case goal.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case goal.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_goals", value)
			} else if value.Valid {
				_m.user_goals = new(int)
				*_m.user_goals = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Goal.
// This includes values selected through modifiers, order, etc.
func (_m *Goal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Goal entity.
func (_m *Goal) QueryOwner() *UserQuery {
	return NewGoalClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this Goal.
// Note that you need to call Goal.Unwrap() before calling this method if this Goal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Goal) Update() *GoalUpdateOne {
	return NewGoalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Goal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Goal) Unwrap() *Goal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Goal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Goal) String() string {
	var builder strings.Builder
	builder.WriteString("Goal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("target=")
	builder.WriteString(fmt.Sprintf("%v", _m.Target))
	builder.WriteString(", ")
	builder.WriteString("current=")
	builder.WriteString(fmt.Sprintf("%v", _m.Current))
	builder.WriteString(", ")
	builder.WriteString("deadline=")
	builder.WriteString(_m.Deadline.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(_m.Color)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Goals is a parsable slice of Goal.
type Goals []*Goal
