// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/goal"
	"backend/ent/predicate"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoalUpdate is the builder for updating Goal entities.
type GoalUpdate struct {
	config
	hooks    []Hook
	mutation *GoalMutation
}

// Where appends a list predicates to the GoalUpdate builder.
func (_u *GoalUpdate) Where(ps ...predicate.Goal) *GoalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *GoalUpdate) SetName(v string) *GoalUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GoalUpdate) SetNillableName(v *string) *GoalUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *GoalUpdate) SetTarget(v float64) *GoalUpdate {
	_u.mutation.ResetTarget()
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *GoalUpdate) SetNillableTarget(v *float64) *GoalUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// AddTarget adds value to the "target" field.
func (_u *GoalUpdate) AddTarget(v float64) *GoalUpdate {
	_u.mutation.AddTarget(v)
	return _u
}

// SetCurrent sets the "current" field.
func (_u *GoalUpdate) SetCurrent(v float64) *GoalUpdate {
	_u.mutation.ResetCurrent()
	_u.mutation.SetCurrent(v)
	return _u
}

// SetNillableCurrent sets the "current" field if the given value is not nil.
func (_u *GoalUpdate) SetNillableCurrent(v *float64) *GoalUpdate {
	if v != nil {
		_u.SetCurrent(*v)
	}
	return _u
}

// AddCurrent adds value to the "current" field.
func (_u *GoalUpdate) AddCurrent(v float64) *GoalUpdate {
	_u.mutation.AddCurrent(v)
	return _u
}

// SetDeadline sets the "deadline" field.
func (_u *GoalUpdate) SetDeadline(v time.Time) *GoalUpdate {
	_u.mutation.SetDeadline(v)
	return _u
}

// SetNillableDeadline sets the "deadline" field if the given value is not nil.
func (_u *GoalUpdate) SetNillableDeadline(v *time.Time) *GoalUpdate {
	if v != nil {
		_u.SetDeadline(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *GoalUpdate) SetColor(v string) *GoalUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *GoalUpdate) SetNillableColor(v *string) *GoalUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GoalUpdate) SetCreatedAt(v time.Time) *GoalUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GoalUpdate) SetNillableCreatedAt(v *time.Time) *GoalUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *GoalUpdate) SetOwnerID(id int) *GoalUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *GoalUpdate) SetNillableOwnerID(id *int) *GoalUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *GoalUpdate) SetOwner(v *User) *GoalUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the GoalMutation object of the builder.
func (_u *GoalUpdate) Mutation() *GoalMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *GoalUpdate) ClearOwner() *GoalUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GoalUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GoalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GoalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(goal.Table, goal.Columns, sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(goal.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(goal.FieldTarget, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTarget(); ok {
		_spec.AddField(goal.FieldTarget, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Current(); ok {
		_spec.SetField(goal.FieldCurrent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCurrent(); ok {
		_spec.AddField(goal.FieldCurrent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Deadline(); ok {
		_spec.SetField(goal.FieldDeadline, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(goal.FieldColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(goal.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goal.OwnerTable,
			Columns: []string{goal.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goal.OwnerTable,
			Columns: []string{goal.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GoalUpdateOne is the builder for updating a single Goal entity.
type GoalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GoalMutation
}

// SetName sets the "name" field.
func (_u *GoalUpdateOne) SetName(v string) *GoalUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GoalUpdateOne) SetNillableName(v *string) *GoalUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *GoalUpdateOne) SetTarget(v float64) *GoalUpdateOne {
	_u.mutation.ResetTarget()
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *GoalUpdateOne) SetNillableTarget(v *float64) *GoalUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// AddTarget adds value to the "target" field.
func (_u *GoalUpdateOne) AddTarget(v float64) *GoalUpdateOne {
	_u.mutation.AddTarget(v)
	return _u
}

// SetCurrent sets the "current" field.
func (_u *GoalUpdateOne) SetCurrent(v float64) *GoalUpdateOne {
	_u.mutation.ResetCurrent()
	_u.mutation.SetCurrent(v)
	return _u
}

// SetNillableCurrent sets the "current" field if the given value is not nil.
func (_u *GoalUpdateOne) SetNillableCurrent(v *float64) *GoalUpdateOne {
	if v != nil {
		_u.SetCurrent(*v)
	}
	return _u
}

// AddCurrent adds value to the "current" field.
func (_u *GoalUpdateOne) AddCurrent(v float64) *GoalUpdateOne {
	_u.mutation.AddCurrent(v)
	return _u
}

// SetDeadline sets the "deadline" field.
func (_u *GoalUpdateOne) SetDeadline(v time.Time) *GoalUpdateOne {
	_u.mutation.SetDeadline(v)
	return _u
}

// SetNillableDeadline sets the "deadline" field if the given value is not nil.
func (_u *GoalUpdateOne) SetNillableDeadline(v *time.Time) *GoalUpdateOne {
	if v != nil {
		_u.SetDeadline(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *GoalUpdateOne) SetColor(v string) *GoalUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *GoalUpdateOne) SetNillableColor(v *string) *GoalUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GoalUpdateOne) SetCreatedAt(v time.Time) *GoalUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GoalUpdateOne) SetNillableCreatedAt(v *time.Time) *GoalUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *GoalUpdateOne) SetOwnerID(id int) *GoalUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *GoalUpdateOne) SetNillableOwnerID(id *int) *GoalUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *GoalUpdateOne) SetOwner(v *User) *GoalUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the GoalMutation object of the builder.
func (_u *GoalUpdateOne) Mutation() *GoalMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *GoalUpdateOne) ClearOwner() *GoalUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the GoalUpdate builder.
func (_u *GoalUpdateOne) Where(ps ...predicate.Goal) *GoalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GoalUpdateOne) Select(field string, fields ...string) *GoalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Goal entity.
func (_u *GoalUpdateOne) Save(ctx context.Context) (*Goal, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoalUpdateOne) SaveX(ctx context.Context) *Goal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GoalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GoalUpdateOne) sqlSave(ctx context.Context) (_node *Goal, err error) {
	_spec := sqlgraph.NewUpdateSpec(goal.Table, goal.Columns, sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Goal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goal.FieldID)
		for _, f := range fields {
			if !goal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != goal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(goal.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(goal.FieldTarget, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTarget(); ok {
		_spec.AddField(goal.FieldTarget, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Current(); ok {
		_spec.SetField(goal.FieldCurrent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCurrent(); ok {
		_spec.AddField(goal.FieldCurrent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Deadline(); ok {
		_spec.SetField(goal.FieldDeadline, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(goal.FieldColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(goal.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goal.OwnerTable,
			Columns: []string{goal.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goal.OwnerTable,
			Columns: []string{goal.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Goal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
