// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/goal"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoalCreate is the builder for creating a Goal entity.
type GoalCreate struct {
	config
	mutation *GoalMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *GoalCreate) SetName(v string) *GoalCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTarget sets the "target" field.
func (_c *GoalCreate) SetTarget(v float64) *GoalCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetCurrent sets the "current" field.
func (_c *GoalCreate) SetCurrent(v float64) *GoalCreate {
	_c.mutation.SetCurrent(v)
	return _c
}

// SetNillableCurrent sets the "current" field if the given value is not nil.
func (_c *GoalCreate) SetNillableCurrent(v *float64) *GoalCreate {
	if v != nil {
		_c.SetCurrent(*v)
	}
	return _c
}

// SetDeadline sets the "deadline" field.
func (_c *GoalCreate) SetDeadline(v time.Time) *GoalCreate {
	_c.mutation.SetDeadline(v)
	return _c
}

// SetColor sets the "color" field.
func (_c *GoalCreate) SetColor(v string) *GoalCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GoalCreate) SetCreatedAt(v time.Time) *GoalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GoalCreate) SetNillableCreatedAt(v *time.Time) *GoalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *GoalCreate) SetOwnerID(id int) *GoalCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_c *GoalCreate) SetNillableOwnerID(id *int) *GoalCreate {
	if id != nil {
		_c = _c.SetOwnerID(*id)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *GoalCreate) SetOwner(v *User) *GoalCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the GoalMutation object of the builder.
func (_c *GoalCreate) Mutation() *GoalMutation {
	return _c.mutation
}

// Save creates the Goal in the database.
func (_c *GoalCreate) Save(ctx context.Context) (*Goal, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GoalCreate) SaveX(ctx context.Context) *Goal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GoalCreate) defaults() {
	if _, ok := _c.mutation.Current(); !ok {
		v := goal.DefaultCurrent
		_c.mutation.SetCurrent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := goal.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GoalCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Goal.name"`)}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "Goal.target"`)}
	}
	if _, ok := _c.mutation.Current(); !ok {
		return &ValidationError{Name: "current", err: errors.New(`ent: missing required field "Goal.current"`)}
	}
	if _, ok := _c.mutation.Deadline(); !ok {
		return &ValidationError{Name: "deadline", err: errors.New(`ent: missing required field "Goal.deadline"`)}
	}
	if _, ok := _c.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "Goal.color"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Goal.created_at"`)}
	}
	return nil
}

func (_c *GoalCreate) sqlSave(ctx context.Context) (*Goal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GoalCreate) createSpec() (*Goal, *sqlgraph.CreateSpec) {
	var (
		_node = &Goal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(goal.Table, sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(goal.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(goal.FieldTarget, field.TypeFloat64, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Current(); ok {
		_spec.SetField(goal.FieldCurrent, field.TypeFloat64, value)
		_node.Current = value
	}
	if value, ok := _c.mutation.Deadline(); ok {
		_spec.SetField(goal.FieldDeadline, field.TypeTime, value)
		_node.Deadline = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(goal.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(goal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goal.OwnerTable,
			Columns: []string{goal.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_goals = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GoalCreateBulk is the builder for creating many Goal entities in bulk.
type GoalCreateBulk struct {
	config
	err      error
	builders []*GoalCreate
}

// Save creates the Goal entities in the database.
func (_c *GoalCreateBulk) Save(ctx context.Context) ([]*Goal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Goal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GoalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GoalCreateBulk) SaveX(ctx context.Context) []*Goal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
