// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/account"
	"backend/ent/budgetrule"
	"backend/ent/category"
	"backend/ent/goal"
	"backend/ent/schema"
	"backend/ent/transaction"
	"backend/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescBalance is the schema descriptor for balance field.
	accountDescBalance := accountFields[2].Descriptor()
	// account.DefaultBalance holds the default value on creation for the balance field.
	account.DefaultBalance = accountDescBalance.Default.(float64)
	// accountDescLimit is the schema descriptor for limit field.
	accountDescLimit := accountFields[5].Descriptor()
	// account.DefaultLimit holds the default value on creation for the limit field.
	account.DefaultLimit = accountDescLimit.Default.(float64)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[6].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	budgetruleFields := schema.BudgetRule{}.Fields()
	_ = budgetruleFields
	// budgetruleDescCreatedAt is the schema descriptor for created_at field.
	budgetruleDescCreatedAt := budgetruleFields[4].Descriptor()
	// budgetrule.DefaultCreatedAt holds the default value on creation for the created_at field.
	budgetrule.DefaultCreatedAt = budgetruleDescCreatedAt.Default.(func() time.Time)
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[4].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	goalFields := schema.Goal{}.Fields()
	_ = goalFields
	// goalDescCurrent is the schema descriptor for current field.
	goalDescCurrent := goalFields[2].Descriptor()
	// goal.DefaultCurrent holds the default value on creation for the current field.
	goal.DefaultCurrent = goalDescCurrent.Default.(float64)
	// goalDescCreatedAt is the schema descriptor for created_at field.
	goalDescCreatedAt := goalFields[5].Descriptor()
	// goal.DefaultCreatedAt holds the default value on creation for the created_at field.
	goal.DefaultCreatedAt = goalDescCreatedAt.Default.(func() time.Time)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescIsRecurring is the schema descriptor for is_recurring field.
	transactionDescIsRecurring := transactionFields[6].Descriptor()
	// transaction.DefaultIsRecurring holds the default value on creation for the is_recurring field.
	transaction.DefaultIsRecurring = transactionDescIsRecurring.Default.(bool)
	// transactionDescNotificationActive is the schema descriptor for notification_active field.
	transactionDescNotificationActive := transactionFields[7].Descriptor()
	// transaction.DefaultNotificationActive holds the default value on creation for the notification_active field.
	transaction.DefaultNotificationActive = transactionDescNotificationActive.Default.(bool)
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[8].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
