// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/account"
	"backend/ent/predicate"
	"backend/ent/transaction"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionMutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDescription sets the "description" field.
func (_u *TransactionUpdate) SetDescription(v string) *TransactionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableDescription(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionUpdate) SetAmount(v float64) *TransactionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableAmount(v *float64) *TransactionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionUpdate) AddAmount(v float64) *TransactionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetType sets the "type" field.
func (_u *TransactionUpdate) SetType(v string) *TransactionUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableType(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *TransactionUpdate) SetDate(v time.Time) *TransactionUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableDate(v *time.Time) *TransactionUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *TransactionUpdate) SetCategory(v string) *TransactionUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableCategory(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *TransactionUpdate) SetPaymentMethod(v string) *TransactionUpdate {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillablePaymentMethod(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// ClearPaymentMethod clears the value of the "payment_method" field.
func (_u *TransactionUpdate) ClearPaymentMethod() *TransactionUpdate {
	_u.mutation.ClearPaymentMethod()
	return _u
}

// SetIsRecurring sets the "is_recurring" field.
func (_u *TransactionUpdate) SetIsRecurring(v bool) *TransactionUpdate {
	_u.mutation.SetIsRecurring(v)
	return _u
}

// SetNillableIsRecurring sets the "is_recurring" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableIsRecurring(v *bool) *TransactionUpdate {
	if v != nil {
		_u.SetIsRecurring(*v)
	}
	return _u
}

// SetNotificationActive sets the "notification_active" field.
func (_u *TransactionUpdate) SetNotificationActive(v bool) *TransactionUpdate {
	_u.mutation.SetNotificationActive(v)
	return _u
}

// SetNillableNotificationActive sets the "notification_active" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableNotificationActive(v *bool) *TransactionUpdate {
	if v != nil {
		_u.SetNotificationActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TransactionUpdate) SetCreatedAt(v time.Time) *TransactionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableCreatedAt(v *time.Time) *TransactionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *TransactionUpdate) SetOwnerID(id int) *TransactionUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *TransactionUpdate) SetNillableOwnerID(id *int) *TransactionUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *TransactionUpdate) SetOwner(v *User) *TransactionUpdate {
	return _u.SetOwnerID(v.ID)
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *TransactionUpdate) SetAccountID(id int) *TransactionUpdate {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetNillableAccountID sets the "account" edge to the Account entity by ID if the given value is not nil.
func (_u *TransactionUpdate) SetNillableAccountID(id *int) *TransactionUpdate {
	if id != nil {
		_u = _u.SetAccountID(*id)
	}
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *TransactionUpdate) SetAccount(v *Account) *TransactionUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdate) Mutation() *TransactionMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *TransactionUpdate) ClearOwner() *TransactionUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *TransactionUpdate) ClearAccount() *TransactionUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(transaction.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(transaction.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(transaction.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(transaction.FieldPaymentMethod, field.TypeString, value)
	}
	if _u.mutation.PaymentMethodCleared() {
		_spec.ClearField(transaction.FieldPaymentMethod, field.TypeString)
	}
	if value, ok := _u.mutation.IsRecurring(); ok {
		_spec.SetField(transaction.FieldIsRecurring, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotificationActive(); ok {
		_spec.SetField(transaction.FieldNotificationActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(transaction.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.OwnerTable,
			Columns: []string{transaction.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.OwnerTable,
			Columns: []string{transaction.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionMutation
}

// SetDescription sets the "description" field.
func (_u *TransactionUpdateOne) SetDescription(v string) *TransactionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableDescription(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionUpdateOne) SetAmount(v float64) *TransactionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableAmount(v *float64) *TransactionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionUpdateOne) AddAmount(v float64) *TransactionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetType sets the "type" field.
func (_u *TransactionUpdateOne) SetType(v string) *TransactionUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableType(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *TransactionUpdateOne) SetDate(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableDate(v *time.Time) *TransactionUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *TransactionUpdateOne) SetCategory(v string) *TransactionUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableCategory(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *TransactionUpdateOne) SetPaymentMethod(v string) *TransactionUpdateOne {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillablePaymentMethod(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// ClearPaymentMethod clears the value of the "payment_method" field.
func (_u *TransactionUpdateOne) ClearPaymentMethod() *TransactionUpdateOne {
	_u.mutation.ClearPaymentMethod()
	return _u
}

// SetIsRecurring sets the "is_recurring" field.
func (_u *TransactionUpdateOne) SetIsRecurring(v bool) *TransactionUpdateOne {
	_u.mutation.SetIsRecurring(v)
	return _u
}

// SetNillableIsRecurring sets the "is_recurring" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableIsRecurring(v *bool) *TransactionUpdateOne {
	if v != nil {
		_u.SetIsRecurring(*v)
	}
	return _u
}

// SetNotificationActive sets the "notification_active" field.
func (_u *TransactionUpdateOne) SetNotificationActive(v bool) *TransactionUpdateOne {
	_u.mutation.SetNotificationActive(v)
	return _u
}

// SetNillableNotificationActive sets the "notification_active" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableNotificationActive(v *bool) *TransactionUpdateOne {
	if v != nil {
		_u.SetNotificationActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TransactionUpdateOne) SetCreatedAt(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableCreatedAt(v *time.Time) *TransactionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *TransactionUpdateOne) SetOwnerID(id int) *TransactionUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableOwnerID(id *int) *TransactionUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *TransactionUpdateOne) SetOwner(v *User) *TransactionUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *TransactionUpdateOne) SetAccountID(id int) *TransactionUpdateOne {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetNillableAccountID sets the "account" edge to the Account entity by ID if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableAccountID(id *int) *TransactionUpdateOne {
	if id != nil {
		_u = _u.SetAccountID(*id)
	}
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *TransactionUpdateOne) SetAccount(v *Account) *TransactionUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdateOne) Mutation() *TransactionMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *TransactionUpdateOne) ClearOwner() *TransactionUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *TransactionUpdateOne) ClearAccount() *TransactionUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdateOne) Where(ps ...predicate.Transaction) *TransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Transaction entity.
func (_u *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(transaction.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(transaction.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(transaction.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(transaction.FieldPaymentMethod, field.TypeString, value)
	}
	if _u.mutation.PaymentMethodCleared() {
		_spec.ClearField(transaction.FieldPaymentMethod, field.TypeString)
	}
	if value, ok := _u.mutation.IsRecurring(); ok {
		_spec.SetField(transaction.FieldIsRecurring, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotificationActive(); ok {
		_spec.SetField(transaction.FieldNotificationActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(transaction.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.OwnerTable,
			Columns: []string{transaction.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.OwnerTable,
			Columns: []string{transaction.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Transaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
