// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "balance", Type: field.TypeFloat64, Default: 0},
		{Name: "institution", Type: field.TypeString},
		{Name: "color", Type: field.TypeString},
		{Name: "limit", Type: field.TypeFloat64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_accounts", Type: field.TypeInt, Nullable: true},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "accounts_users_accounts",
				Columns:    []*schema.Column{AccountsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// BudgetRulesColumns holds the columns for the "budget_rules" table.
	BudgetRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "label", Type: field.TypeString},
		{Name: "category", Type: field.TypeString},
		{Name: "percentage", Type: field.TypeFloat64},
		{Name: "color", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_budget_rules", Type: field.TypeInt, Nullable: true},
	}
	// BudgetRulesTable holds the schema information for the "budget_rules" table.
	BudgetRulesTable = &schema.Table{
		Name:       "budget_rules",
		Columns:    BudgetRulesColumns,
		PrimaryKey: []*schema.Column{BudgetRulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "budget_rules_users_budget_rules",
				Columns:    []*schema.Column{BudgetRulesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString},
		{Name: "color", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_categories", Type: field.TypeInt, Nullable: true},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "categories_users_categories",
				Columns:    []*schema.Column{CategoriesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// GoalsColumns holds the columns for the "goals" table.
	GoalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "target", Type: field.TypeFloat64},
		{Name: "current", Type: field.TypeFloat64, Default: 0},
		{Name: "deadline", Type: field.TypeTime},
		{Name: "color", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_goals", Type: field.TypeInt, Nullable: true},
	}
	// GoalsTable holds the schema information for the "goals" table.
	GoalsTable = &schema.Table{
		Name:       "goals",
		Columns:    GoalsColumns,
		PrimaryKey: []*schema.Column{GoalsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "goals_users_goals",
				Columns:    []*schema.Column{GoalsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "type", Type: field.TypeString},
		{Name: "date", Type: field.TypeTime},
		{Name: "category", Type: field.TypeString},
		{Name: "payment_method", Type: field.TypeString, Nullable: true},
		{Name: "is_recurring", Type: field.TypeBool, Default: false},
		{Name: "notification_active", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "account_transactions", Type: field.TypeInt, Nullable: true},
		{Name: "user_transactions", Type: field.TypeInt, Nullable: true},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transactions_accounts_transactions",
				Columns:    []*schema.Column{TransactionsColumns[10]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "transactions_users_transactions",
				Columns:    []*schema.Column{TransactionsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "userVitalicio", "userMensal", "UserExperimental"}, Default: "UserExperimental"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		BudgetRulesTable,
		CategoriesTable,
		GoalsTable,
		TransactionsTable,
		UsersTable,
	}
)

func init() {
	AccountsTable.ForeignKeys[0].RefTable = UsersTable
	BudgetRulesTable.ForeignKeys[0].RefTable = UsersTable
	CategoriesTable.ForeignKeys[0].RefTable = UsersTable
	GoalsTable.ForeignKeys[0].RefTable = UsersTable
	TransactionsTable.ForeignKeys[0].RefTable = AccountsTable
	TransactionsTable.ForeignKeys[1].RefTable = UsersTable
}
