// Code generated by ent, DO NOT EDIT.

package budgetrule

import (
	"backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldLTE(FieldID, id))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEQ(FieldCategory, v))
}

// Percentage applies equality check predicate on the "percentage" field. It's identical to PercentageEQ.
func Percentage(v float64) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEQ(FieldPercentage, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEQ(FieldColor, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEQ(FieldCreatedAt, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldContainsFold(FieldLabel, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldContainsFold(FieldCategory, v))
}

// PercentageEQ applies the EQ predicate on the "percentage" field.
func PercentageEQ(v float64) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEQ(FieldPercentage, v))
}

// PercentageNEQ applies the NEQ predicate on the "percentage" field.
func PercentageNEQ(v float64) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldNEQ(FieldPercentage, v))
}

// PercentageIn applies the In predicate on the "percentage" field.
func PercentageIn(vs ...float64) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldIn(FieldPercentage, vs...))
}

// PercentageNotIn applies the NotIn predicate on the "percentage" field.
func PercentageNotIn(vs ...float64) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldNotIn(FieldPercentage, vs...))
}

// PercentageGT applies the GT predicate on the "percentage" field.
func PercentageGT(v float64) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldGT(FieldPercentage, v))
}

// PercentageGTE applies the GTE predicate on the "percentage" field.
func PercentageGTE(v float64) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldGTE(FieldPercentage, v))
}

// PercentageLT applies the LT predicate on the "percentage" field.
func PercentageLT(v float64) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldLT(FieldPercentage, v))
}

// PercentageLTE applies the LTE predicate on the "percentage" field.
func PercentageLTE(v float64) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldLTE(FieldPercentage, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "color" field.
func ColorContains(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "color" field.
func ColorHasPrefix(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "color" field.
func ColorHasSuffix(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldHasSuffix(FieldColor, v))
}

// ColorEqualFold applies the EqualFold predicate on the "color" field.
func ColorEqualFold(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "color" field.
func ColorContainsFold(v string) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldContainsFold(FieldColor, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BudgetRule {
	return predicate.BudgetRule(sql.FieldLTE(FieldCreatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.BudgetRule {
	return predicate.BudgetRule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.BudgetRule {
	return predicate.BudgetRule(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BudgetRule) predicate.BudgetRule {
	return predicate.BudgetRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BudgetRule) predicate.BudgetRule {
	return predicate.BudgetRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BudgetRule) predicate.BudgetRule {
	return predicate.BudgetRule(sql.NotPredicates(p))
}
